/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import businessLogic.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author Federico
 */
public class Interfaz extends javax.swing.JFrame {

	ProxyManager pm = new ProxyManager();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        setTitle("Videoclub");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obtenerPelículaPorTítuloPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        obtenerPeliculaPorTituloTitulo = new javax.swing.JTextField();
        obtenerPelículaPorTítuloObtener = new javax.swing.JButton();
        obtenerPeliculaPorTituloResultado = new javax.swing.JLabel();
        obtenerUsuarioPorNombrePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        obtenerUsuarioPorNombreNombre = new javax.swing.JTextField();
        obtenerUsuarioPorNombreObtener = new javax.swing.JButton();
        obtenerUsuarioPorNombreResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        listarPeliculas = new javax.swing.JRadioButton();
        listarUsuarios = new javax.swing.JRadioButton();
        listarPrestamos = new javax.swing.JRadioButton();
        listarListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        obtenerPelículaPorTítuloPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Obtener película por título:");

        obtenerPeliculaPorTituloTitulo.setText("Título de la película");

        obtenerPelículaPorTítuloObtener.setText("Obtener");
        obtenerPelículaPorTítuloObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerPelículaPorTítuloObtenerActionPerformed(evt);
            }
        });

        obtenerPeliculaPorTituloResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout obtenerPelículaPorTítuloPanelLayout = new javax.swing.GroupLayout(obtenerPelículaPorTítuloPanel);
        obtenerPelículaPorTítuloPanel.setLayout(obtenerPelículaPorTítuloPanelLayout);
        obtenerPelículaPorTítuloPanelLayout.setHorizontalGroup(
            obtenerPelículaPorTítuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obtenerPelículaPorTítuloPanelLayout.createSequentialGroup()
                .addGroup(obtenerPelículaPorTítuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(obtenerPelículaPorTítuloPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(obtenerPeliculaPorTituloTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obtenerPelículaPorTítuloObtener))
                    .addGroup(obtenerPelículaPorTítuloPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(obtenerPeliculaPorTituloResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        obtenerPelículaPorTítuloPanelLayout.setVerticalGroup(
            obtenerPelículaPorTítuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obtenerPelículaPorTítuloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obtenerPelículaPorTítuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(obtenerPeliculaPorTituloTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenerPelículaPorTítuloObtener))
                .addGap(29, 29, 29)
                .addComponent(obtenerPeliculaPorTituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        obtenerUsuarioPorNombrePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Obtener usuario por nombre:");

        obtenerUsuarioPorNombreNombre.setText("Nombre del usuario");

        obtenerUsuarioPorNombreObtener.setText("Obtener");
        obtenerUsuarioPorNombreObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerUsuarioPorNombreObtenerActionPerformed(evt);
            }
        });

        obtenerUsuarioPorNombreResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout obtenerUsuarioPorNombrePanelLayout = new javax.swing.GroupLayout(obtenerUsuarioPorNombrePanel);
        obtenerUsuarioPorNombrePanel.setLayout(obtenerUsuarioPorNombrePanelLayout);
        obtenerUsuarioPorNombrePanelLayout.setHorizontalGroup(
            obtenerUsuarioPorNombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obtenerUsuarioPorNombrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obtenerUsuarioPorNombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(obtenerUsuarioPorNombrePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obtenerUsuarioPorNombreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(obtenerUsuarioPorNombrePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(obtenerUsuarioPorNombreResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obtenerUsuarioPorNombreObtener)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        obtenerUsuarioPorNombrePanelLayout.setVerticalGroup(
            obtenerUsuarioPorNombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obtenerUsuarioPorNombrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obtenerUsuarioPorNombrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(obtenerUsuarioPorNombreNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenerUsuarioPorNombreObtener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(obtenerUsuarioPorNombreResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Listar");

        listarPeliculas.setSelected(true);
        listarPeliculas.setText("películas");

        listarUsuarios.setText("usuarios");

        listarPrestamos.setText("préstamos");

        listarListar.setText("Listar");
        listarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarListarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(listarPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listarUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarPrestamos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listarListar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listarPeliculas)
                    .addComponent(listarUsuarios)
                    .addComponent(listarPrestamos)
                    .addComponent(listarListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(obtenerPelículaPorTítuloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(obtenerUsuarioPorNombrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(obtenerPelículaPorTítuloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(obtenerUsuarioPorNombrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerUsuarioPorNombreObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerUsuarioPorNombreObtenerActionPerformed
        String nombre = obtenerUsuarioPorNombreNombre.getText();
        Usuario u = pm.obtenerUsuarioPorNombre(nombre);
        obtenerUsuarioPorNombreResultado.setText(u.getNombre());
    }//GEN-LAST:event_obtenerUsuarioPorNombreObtenerActionPerformed

    private void listarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarListarActionPerformed
        DefaultListModel model = new DefaultListModel();
        
        if (listarPeliculas.isSelected()) {
            for (Pelicula p : pm.listarPeliculas()) {
                model.addElement(p);
            }
        }
        
        if (listarUsuarios.isSelected()) {
            for (Usuario u : pm.listarUsuarios()) {
                model.addElement(u);
            }
        }
        
        if (listarPrestamos.isSelected()) {
            for (Prestamo pr : pm.listarPrestamos()) {
                model.addElement(pr);
            }
        }
    }//GEN-LAST:event_listarListarActionPerformed

    private void obtenerPelículaPorTítuloObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerPelículaPorTítuloObtenerActionPerformed
        String titulo = obtenerPeliculaPorTituloTitulo.getText();
        Pelicula p = pm.obtenerPeliculaPorTitulo(titulo);
        obtenerPeliculaPorTituloResultado.setText(p.getTitulo());
    }//GEN-LAST:event_obtenerPelículaPorTítuloObtenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarListar;
    private javax.swing.JRadioButton listarPeliculas;
    private javax.swing.JRadioButton listarPrestamos;
    private javax.swing.JRadioButton listarUsuarios;
    private javax.swing.JLabel obtenerPeliculaPorTituloResultado;
    private javax.swing.JTextField obtenerPeliculaPorTituloTitulo;
    private javax.swing.JButton obtenerPelículaPorTítuloObtener;
    private javax.swing.JPanel obtenerPelículaPorTítuloPanel;
    private javax.swing.JTextField obtenerUsuarioPorNombreNombre;
    private javax.swing.JButton obtenerUsuarioPorNombreObtener;
    private javax.swing.JPanel obtenerUsuarioPorNombrePanel;
    private javax.swing.JLabel obtenerUsuarioPorNombreResultado;
    // End of variables declaration//GEN-END:variables
}
